/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MarkdowntohtmlComponent {
    'content': string;
  }
  interface MarkdowntohtmlComponentAttributes extends StencilHTMLAttributes {
    'content'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MarkdowntohtmlComponent': Components.MarkdowntohtmlComponent;
  }

  interface StencilIntrinsicElements {
    'markdowntohtml-component': Components.MarkdowntohtmlComponentAttributes;
  }


  interface HTMLMarkdowntohtmlComponentElement extends Components.MarkdowntohtmlComponent, HTMLStencilElement {}
  var HTMLMarkdowntohtmlComponentElement: {
    prototype: HTMLMarkdowntohtmlComponentElement;
    new (): HTMLMarkdowntohtmlComponentElement;
  };

  interface HTMLElementTagNameMap {
    'markdowntohtml-component': HTMLMarkdowntohtmlComponentElement
  }

  interface ElementTagNameMap {
    'markdowntohtml-component': HTMLMarkdowntohtmlComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
